Repository 3Pi-Mini3/Mini3Project, pull requests merged in 2024-08, with the labels that each got.

#3 feat: add recommendation, reflection, and skill model
  Mini3Project/Model/Recommendation.swift
  Mini3Project/Model/Reflection.swift
  Mini3Project/Model/Skill.swift
Labels: enhancement

#4 feat: create add gemini generative ai service
  Config.plist
  Mini3Project/Services/GenerativeAI/GenerativeAIService.swift
Labels: enhancement

#8 feat: add tab bar view and chatbot view
  Mini3Project/Resources/Assets.xcassets/ColorPallette/MascotMode/Primary/MascotBShade100.colorset/Contents.json
  Mini3Project/Resources/Assets.xcassets/ColorPallette/MascotMode/Primary/MascotBTint 100.colorset/Contents.json
  Mini3Project/Resources/Assets.xcassets/ColorPallette/MascotMode/Primary/MascotBTone100.colorset/Contents.json
  Mini3Project/Resources/Assets.xcassets/ColorPallette/MascotMode/YellowBee.colorset/Contents.json
  Mini3Project/Resources/Assets.xcassets/ColorPallette/MascotMode/YellowButton.colorset/Contents.json
  Mini3Project/SceneDelegate.swift
  Mini3Project/View/ChatViewController.swift
  Mini3Project/View/Components/CustomTabBarController.swift
  Mini3Project/View/MainViewController.swift
Labels: enhancement

#17 feat: add skill static page
  Mini3Project/View/Components/CardView.swift
  Mini3Project/View/Components/CardViewController.swift
  Mini3Project/View/Components/CustomTabBarController.swift
  Mini3Project/View/Components/SkillsContentViewController.swift
  Mini3Project/View/DetailSkillViewController.swift
  Mini3Project/View/ReflectionViewController.swift
  Mini3Project/View/SkillsViewController.swift
Labels: enhancement

#22 Feature/bridge chat view
  Mini3Project/Resources/Assets.xcassets/4stages.imageset/4stages.png
  Mini3Project/Resources/Assets.xcassets/4stages.imageset/Contents.json
  Mini3Project/Resources/Assets.xcassets/ColorPallette/AdditionalColors/Color.colorset/Contents.json
  Mini3Project/Resources/Assets.xcassets/ColorPallette/AdditionalColors/Contents.json
  Mini3Project/Resources/Assets.xcassets/duration.imageset/Contents.json
  Mini3Project/Resources/Assets.xcassets/duration.imageset/duration.png
  Mini3Project/View/BridgeChatViewController.swift
Labels: enhancement

#23 feat: create new reflection logic
  Mini3Project/Config.plist
  Mini3Project/Model/Reflection.swift
  Mini3Project/Services/GenerativeAI/GenerativeAIService.swift
  Mini3Project/View/Components/CustomTabBarController.swift
  Mini3Project/View/MainViewController.swift
  Mini3Project/View/ReflectionDetail/ReflectionsDetailViewController.swift
  Mini3Project/ViewModel/Reflections/ReflectionsViewModel.swift
Labels: enhancement

#28 feat: add splash screen and add bridge gate view
  Mini3Project/Resources/Assets.xcassets/gate1.imageset/Contents.json
  Mini3Project/Resources/Assets.xcassets/gate1.imageset/gate1.png
  Mini3Project/Resources/Assets.xcassets/gate3.imageset/Contents.json
  Mini3Project/Resources/Assets.xcassets/gate3.imageset/gate3.png
  Mini3Project/Resources/Assets.xcassets/logobee.imageset/Contents.json
  Mini3Project/Resources/Assets.xcassets/logobee.imageset/logobee.png
  Mini3Project/View/Base.lproj/LaunchScreen.storyboard
  Mini3Project/View/BridgeChatViewController.swift
  Mini3Project/View/BridgeGateViewController.swift
Labels: enhancement

#29 Feat: Adding input page and Reflection chat page
  Mini3Project/Helpers/Extensions/ProjectTitleInputViewController+UIComponents.swift
  Mini3Project/Helpers/Extensions/ReflectionChatView+UIComponents.swift
  Mini3Project/Helpers/Extensions/ReflectionChatViewController+KeyboardHandler.swift
  Mini3Project/Helpers/Extensions/ReflectionChatViewController+ProgressHandling.swift
  Mini3Project/Resources/Assets.xcassets/ReflectionsInput.imageset/Contents.json
  Mini3Project/Resources/Assets.xcassets/ReflectionsInput.imageset/ReflectionsInputDM.png
  Mini3Project/Resources/Assets.xcassets/ReflectionsInput.imageset/reflectionsInput.png
  Mini3Project/Resources/Assets.xcassets/confirmationMascot.imageset/Contents.json
  Mini3Project/Resources/Assets.xcassets/confirmationMascot.imageset/confirmationDM.png
  Mini3Project/Resources/Assets.xcassets/confirmationMascot.imageset/confirmationLM.png
  Mini3Project/View/BubbleChatCollectionViewCell.swift
  Mini3Project/View/Components/ChatBubbleView.swift
  Mini3Project/View/Components/MascotImageView.swift
  Mini3Project/View/Components/ProgressBarView.swift
  Mini3Project/View/ProjectTitleInputViewController.swift
  Mini3Project/View/ReflectionChatViewController.swift
  Mini3Project/ViewModel/ReflectionChatViewModel.swift
Labels: enhancement

#30 feat: add confirmation view
  Mini3Project/View/Components/ConfirmationView.swift
  Mini3Project/View/ReflectionChatViewController.swift
Labels: enhancement

#32 refactor: some code and feat: add Bridge next page
  Mini3Project/Constants/BridgeGate.swift
  Mini3Project/Constants/ReflectionQuestions.swift
  Mini3Project/Resources/Assets.xcassets/ColorPallette/NeutralColors/Contrasttext.colorset/Contents.json
  Mini3Project/Resources/Assets.xcassets/NextMascot.imageset/Contents.json
  Mini3Project/Resources/Assets.xcassets/NextMascot.imageset/NextMascot.png
  Mini3Project/Resources/Assets.xcassets/gate2.imageset/Contents.json
  Mini3Project/Resources/Assets.xcassets/gate2.imageset/gate2.png
  Mini3Project/Resources/Assets.xcassets/gate4.imageset/Contents.json
  Mini3Project/Resources/Assets.xcassets/gate4.imageset/gate4lm.png
  Mini3Project/Resources/Assets.xcassets/projectNameMascot.imageset/Contents.json
  Mini3Project/Resources/Assets.xcassets/projectNameMascot.imageset/projectNameDM.png
  Mini3Project/Resources/Assets.xcassets/projectNameMascot.imageset/projectNameLM.png
  Mini3Project/View/BridgeChatViewController.swift
  Mini3Project/View/BridgeGateViewController.swift
  Mini3Project/View/BridgeNextViewController.swift
  Mini3Project/View/Components/CustomTabBarController.swift
  Mini3Project/View/ProjectTitleInputViewController.swift
  Mini3Project/View/ReflectionChatViewController.swift
  Mini3Project/View/ReflectionDetail/ReflectionsDetailViewController.swift
  Mini3Project/ViewModel/ReflectionChatViewModel.swift
Labels: bug, enhancement

#31 fix: fix skill data flow
  Mini3Project/Model/Skill.swift
  Mini3Project/Resources/Assets.xcassets/SittingBee.imageset/Contents.json
  Mini3Project/Resources/Assets.xcassets/SittingBee.imageset/SittingBee.png
  Mini3Project/View/Components/SkillsContentViewController.swift
  Mini3Project/View/DetailSkillViewController.swift
  Mini3Project/View/MainViewController.swift
  Mini3Project/View/SkillsListViewController.swift
  Mini3Project/View/SkillsViewController.swift
  Mini3Project/ViewModel/SkillsViewModel.swift
Labels: bug

#38 Adding and refactor some code
  Mini3Project/AppDelegate.swift
  Mini3Project/Constants/BridgeGate.swift
  Mini3Project/Helpers/Extensions/ReflectionChatView+UIComponents.swift
  Mini3Project/Helpers/Extensions/ReflectionChatViewController+ProgressHandling.swift
  Mini3Project/Info.plist
  Mini3Project/Model/Reflection.swift
  Mini3Project/Resources/Assets.xcassets/ColorPallette/Additional/AlertBG.colorset/Contents.json
  Mini3Project/Resources/Assets.xcassets/HalloMascot.imageset/Contents.json
  Mini3Project/Resources/Assets.xcassets/HalloMascot.imageset/HalloMascotDM.png
  Mini3Project/Resources/Assets.xcassets/HalloMascot.imageset/HalloMascotLM.png
  Mini3Project/SceneDelegate.swift
  Mini3Project/View/BridgeChatViewController.swift
  Mini3Project/View/BridgeGateViewController.swift
  Mini3Project/View/BridgeNextViewController.swift
  Mini3Project/View/Components/ConfirmationView.swift
  Mini3Project/View/Components/CustomTabBarController.swift
  Mini3Project/View/Components/SkillsContentViewController.swift
  Mini3Project/View/ConfirmationViewController.swift
  Mini3Project/View/MainViewController.swift
  Mini3Project/View/OnboardingViewController.swift
  Mini3Project/View/ProjectTitleInputViewController.swift
  Mini3Project/View/ReflectionChatViewController.swift
  Mini3Project/View/ReflectionDetail/ReflectionsDetailViewController.swift
  Mini3Project/View/Reflections/ReflectionsViewController.swift
  Mini3Project/View/SkillsListViewController.swift
  Mini3Project/View/SkillsViewController.swift
  Mini3Project/ViewModel/BridgeNextViewModel.swift
  Mini3Project/ViewModel/ReflectionChatViewModel.swift
  Mini3Project/ViewModel/Reflections/ReflectionsViewModel.swift
Labels: bug, enhancement

#39 Merge updates from develop into main
  Mini3Project/AppDelegate.swift
  Mini3Project/Constants/BridgeGate.swift
  Mini3Project/Helpers/Extensions/ReflectionChatView+UIComponents.swift
  Mini3Project/Helpers/Extensions/ReflectionChatViewController+ProgressHandling.swift
  Mini3Project/Info.plist
  Mini3Project/Model/Reflection.swift
  Mini3Project/Resources/Assets.xcassets/ColorPallette/Additional/AlertBG.colorset/Contents.json
  Mini3Project/Resources/Assets.xcassets/HalloMascot.imageset/Contents.json
  Mini3Project/Resources/Assets.xcassets/HalloMascot.imageset/HalloMascotDM.png
  Mini3Project/Resources/Assets.xcassets/HalloMascot.imageset/HalloMascotLM.png
  Mini3Project/SceneDelegate.swift
  Mini3Project/View/BridgeChatViewController.swift
  Mini3Project/View/BridgeGateViewController.swift
  Mini3Project/View/BridgeNextViewController.swift
  Mini3Project/View/Components/ConfirmationView.swift
  Mini3Project/View/Components/CustomTabBarController.swift
  Mini3Project/View/Components/SkillsContentViewController.swift
  Mini3Project/View/ConfirmationViewController.swift
  Mini3Project/View/MainViewController.swift
  Mini3Project/View/OnboardingViewController.swift
  Mini3Project/View/ProjectTitleInputViewController.swift
  Mini3Project/View/ReflectionChatViewController.swift
  Mini3Project/View/ReflectionDetail/ReflectionsDetailViewController.swift
  Mini3Project/View/Reflections/ReflectionsViewController.swift
  Mini3Project/View/SkillsListViewController.swift
  Mini3Project/View/SkillsViewController.swift
  Mini3Project/ViewModel/BridgeNextViewModel.swift
  Mini3Project/ViewModel/ReflectionChatViewModel.swift
  Mini3Project/ViewModel/Reflections/ReflectionsViewModel.swift
Labels: bug, enhancement
